In [2]:
pwd

'C:\\Users\\iibm'

In [3]:
print("WORKSHOP ON PYTHON")

WORKSHOP ON PYTHON


In [4]:
print('zhi')

zhi


In [5]:
print('a \'a\'')

a 'a'


In [6]:
print('''a 'alok' ''')

a 'alok' 


In [7]:
print('''
data
science
zhi

''')


data
science
zhi




###Arithmatic Operator

# plus

In [8]:
2+5

7

In [9]:
6-3

3

In [11]:
6+4

10

In [12]:
2*5

10

In [13]:
2**2

4

In [14]:
4/2

2.0

In [15]:
4.2//2

2.0

In [16]:
2e4

20000.0

In [17]:
5*5+8*2

41

In [18]:
(5+5)*2

20

In [19]:
x=10
x

10

In [20]:
x=20

In [21]:
x

20

In [22]:
print(x)

20


In [23]:
type(x)

int

In [24]:
print(type(x))

<class 'int'>


In [25]:
s= 'workshop'

In [26]:
s

'workshop'

#Slicing and Indexing

s[start:end:step]

In [27]:
s[:]

'workshop'

In [28]:
s[: :]

'workshop'

In [29]:
s[5]

'h'

In [30]:
s[:5]

'works'

In [31]:
s[3:]

'kshop'

In [32]:
s[: :2]

'wrso'

In [33]:
s[: : -1]

'pohskrow'

Methods

In [34]:
s=s.upper()

In [35]:
s

'WORKSHOP'

In [36]:
s.lower()

'workshop'

split

In [37]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [40]:
'A B C D E' .split('C')

['A B ', ' D E']

In [42]:
s.split('S')

['WORK', 'HOP']

#Print Property

In [43]:
name='virat'
run=100

In [44]:
print(name+ str(run))

virat100


Formating

# Formating

In [46]:
print('this is a %s pen' %('ram'))

this is a ram pen


In [47]:
print('this is a %s pen %s' %('ram', 'abc'))

this is a ram pen abc


In [48]:
pwd

'C:\\Users\\iibm'

# LIST

In [53]:
my_list='A B C D'.split()

In [54]:
my_list

['A', 'B', 'C', 'D']

In [55]:
mylist=['a' ,5,5.3]

In [56]:
mylist

['a', 5, 5.3]

list

In [57]:
print(type(mylist))

<class 'list'>


# Slicing and Indexing

In [58]:
mylist[1]

5

In [59]:
mylist[0:2]

['a', 5]

In [60]:
mylist[0:3:1]

['a', 5, 5.3]

In [61]:
mylist[0:3:2]

['a', 5.3]

In [62]:
mylist*2

['a', 5, 5.3, 'a', 5, 5.3]

In [63]:
mylist=mylist +['a']

In [64]:
mylist

['a', 5, 5.3, 'a']

##LIST METHOD

## LIST METHOD

In [67]:
1=[1,2,3,4,5]

SyntaxError: cannot assign to literal (<ipython-input-67-b75b889b9ed2>, line 1)

In [68]:
l

NameError: name 'l' is not defined

In [69]:
l=[1,2,3,4,5]

In [70]:
l

[1, 2, 3, 4, 5]

In [72]:
l.append('A B C' .split())

In [73]:
l

[1, 2, 3, 4, 5, 'A', ['A', 'B', 'C']]

In [74]:
l=l.append('A')

In [75]:
print(l)

None


In [76]:
listl=[1,,2,3,4,5]

SyntaxError: invalid syntax (<ipython-input-76-e3c52cedc094>, line 1)

In [77]:
list= [1,,2,3,4,5]

SyntaxError: invalid syntax (<ipython-input-77-ec0b6be6b4c2>, line 1)

In [78]:
list

list

In [79]:
list1

NameError: name 'list1' is not defined

In [80]:
print(list)

<class 'list'>


In [81]:
list.append('a')

TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'str' object

In [82]:
print(type(list))

<class 'type'>


In [83]:
list.append('a')

TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'str' object

In [84]:
list.pop(1)

TypeError: descriptor 'pop' for 'list' objects doesn't apply to a 'int' object

In [85]:
l1=[1,2,3]
l2=[4,5,6]
l3=[6,7,8]

In [86]:
matrix=[l1,l2,l3]

In [87]:
matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [89]:
type(matrix)

list

In [90]:
matrix[1][0]

4

In [91]:
matrix[0][2]

3

In [92]:
len(matrix)

3

# Touple

In [93]:
t1=(1,2,3)

In [94]:
t1

(1, 2, 3)

In [95]:
type(t1)

tuple

In [96]:
print(type(t1))

<class 'tuple'>


In [97]:
t1

(1, 2, 3)

In [98]:
t1[2]

3

In [99]:
l2=[1,,2,3]

SyntaxError: invalid syntax (<ipython-input-99-01ac786df41d>, line 1)

In [100]:
12=[1,2,3]

SyntaxError: cannot assign to literal (<ipython-input-100-4bced23664ee>, line 1)

In [101]:
l1=[1,2,3]

In [102]:
l2[2]=5

In [103]:
l2

[4, 5, 5]

t1[1

In [104]:
t1[1]

2

In [105]:
t1[-1]

3

3 Touple Method

# Touple Method

In [106]:
t1.index(2)

1

In [107]:
t1.count(3)

1

## Dictionary

In [108]:
disc1={1:'a',2:'b',3:'c'}

In [109]:
disc1

{1: 'a', 2: 'b', 3: 'c'}

In [110]:
type(disc1)

dict

In [111]:
print(type(disc1))

<class 'dict'>


In [112]:
disc1[1]

'a'

In [113]:
disc1[2]

'b'

In [114]:
disc1[4]='ram'

In [115]:
disc1

{1: 'a', 2: 'b', 3: 'c', 4: 'ram'}

# Nested Dictionary

In [116]:
disc1={1:'a',2:'b','key1':{1:'a',2:'hellow',3:'c'},3:'c'}

In [117]:
disc1

{1: 'a', 2: 'b', 'key1': {1: 'a', 2: 'hellow', 3: 'c'}, 3: 'c'}

In [118]:
disc1['key1'][2][2]

'l'

In [119]:
disc1['key1'][2]

'hellow'

# Method

In [120]:
disc1.keys()

dict_keys([1, 2, 'key1', 3])

In [122]:
disc1.values()

dict_values(['a', 'b', {1: 'a', 2: 'hellow', 3: 'c'}, 'c'])

In [123]:
disc1.items()

dict_items([(1, 'a'), (2, 'b'), ('key1', {1: 'a', 2: 'hellow', 3: 'c'}), (3, 'c')])

# Set

Unodered Collection

In [124]:
x=st()

NameError: name 'st' is not defined

In [125]:
x=set()

In [126]:
x

set()

In [127]:
type(x)

set

In [128]:
print(type(x))

<class 'set'>


In [129]:
x.add(1)

In [130]:
x

{1}

In [133]:
list2=[1,2,3,1,2,3,2,2,3,4]

In [134]:
list2

[1, 2, 3, 1, 2, 3, 2, 2, 3, 4]

In [135]:
set(list2)

{1, 2, 3, 4}

# Boolean

In [136]:
True

True

In [137]:
False

False

In [138]:
None

In [139]:
list3=[1,2[3,4,'hello']

SyntaxError: unexpected EOF while parsing (<ipython-input-139-a506ab78d989>, line 1)

In [142]:
list3= [1,2,[3,4,'hello']]

In [143]:
list3[2][2]=['goodbye']
list3

[1, 2, [3, 4, ['goodbye']]]

In [144]:
list5=[1,2,33,4,4,11,22,3,3,2]
x=set(list5)
x

{1, 2, 3, 4, 11, 22, 33}

## Membership Operator

In [145]:
m='zhipatna'

In [146]:
m

'zhipatna'

In [147]:
'p' in m

True

In [148]:
't'not in m

False

In [149]:
x=100

In [150]:
y=100

In [151]:
x is y

True

In [152]:
x is not y

False

In [153]:
list1=[1,2,3]

In [154]:
list2=[1,2,3]

In [155]:
list1==list2

True

## Numerical Python

In [156]:
import numpy as np

In [157]:
x =[1,2,4,5]
x

[1, 2, 4, 5]

In [158]:
type(x)

list

In [159]:
y = np.array(x)

In [160]:
type(y)

numpy.ndarray

In [161]:
x2 = (1,2,3,'NIELIT',3.4)

In [162]:
np.array(x2)

array(['1', '2', '3', 'NIELIT', '3.4'], dtype='<U11')

## Linspace

In [165]:
np.linspace(start=0, stop=20, num=10, endpoint=False, retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [166]:
np.linspace(start=0, stop=20,num=10,endpoint=True,retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

## Arange

In [168]:
np.arange(start=0,stop=50,step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [169]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [170]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [171]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

## Create 3*3 Array

In [174]:
z =[[1,2,3],[4,5,6],[7,8,9]]

In [175]:
z

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [178]:
y = np.array(z)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [179]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [180]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [181]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Reshaping

In [182]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

In [183]:
x #1*10 type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Convert to 5*2

In [184]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [185]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [186]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [187]:
x.reshape((1,5))

ValueError: cannot reshape array of size 10 into shape (1,5)

## Sliceing

In [188]:
a = np.arange(10)

In [189]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
s = slice(2,7)

In [191]:
a[s]

array([2, 3, 4, 5, 6])

In [192]:
s1 = slice(2,7,2)

In [193]:
a[s1]

array([2, 4, 6])

In [194]:
a[2:7]

array([2, 3, 4, 5, 6])

In [195]:
a[2:7:2]

array([2, 4, 6])

## Random Number Genration

In [196]:
np.random.rand(5)

array([0.67392084, 0.47776856, 0.32549225, 0.49393644, 0.14282265])

In [197]:
np.random.rand(5)

array([0.14598897, 0.20114039, 0.76551203, 0.54540048, 0.15154142])

## Normal Distribution

In [199]:
np.random.randn(5,4)

array([[-0.30913422, -0.04739367, -0.82861991, -1.13090401],
       [ 0.38828893,  0.38504278,  0.2454935 ,  0.02815104],
       [ 0.64463092,  1.41628356,  0.46863125, -0.46539747],
       [-0.76537816, -0.74377963,  0.81154183,  0.68561982],
       [-1.70317449, -0.61047692,  0.46791741,  1.14327596]])

## Randint

In [200]:
np.random.randint(low=0,high=100)

50

In [201]:
# 4 digit Random Number
np.random.randint(low=100,high=9999)

1707

## seed

In [202]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [204]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])